### ISSUE TITLE
Fails to build with `python setup.py build`

### ISSUE THREAD

**Issue by MehdiChinoune** [mayeut/pybase64#674] opened 2024-01-06 06:48 UTC
Unlike other Python packages, this one fails to build:
```
  running build
  running build_py
  creating build
  creating build/lib.mingw_x86_64_clang-cpython-311
  creating build/lib.mingw_x86_64_clang-cpython-311/pybase64
  copying src/pybase64/_fallback.py -> build/lib.mingw_x86_64_clang-cpython-311/pybase64
  copying src/pybase64/_license.py -> build/lib.mingw_x86_64_clang-cpython-311/pybase64
  copying src/pybase64/_version.py -> build/lib.mingw_x86_64_clang-cpython-311/pybase64
  copying src/pybase64/__init__.py -> build/lib.mingw_x86_64_clang-cpython-311/pybase64
  copying src/pybase64/__main__.py -> build/lib.mingw_x86_64_clang-cpython-311/pybase64
  copying src/pybase64/py.typed -> build/lib.mingw_x86_64_clang-cpython-311/pybase64
  running build_ext
  running cmake '--version'
  cmake version 3.28.1
  
  CMake suite maintained and supported by Kitware (kitware.com/cmake).
  getting cmake extra config
    machine: amd64
    platform: mingw_x86_64_clang
    plat_name: mingw_x86_64_clang
    ARCHFLAGS: None
    CC: clang
    CFLAGS: -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong
    LDFLAGS: -pipe
    sysconfig CC: clang
    sysconfig CCSHARED: 
    sysconfig CFLAGS: -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -O3 -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -O3
    sysconfig BASECFLAGS: 
    sysconfig OPT: -DNDEBUG -g -fwrapv -O3 -Wall
    sysconfig LDFLAGS: -pipe -pipe
  building 'pybase64._pybase64' extension
  creating build/temp.mingw_x86_64_clang-cpython-311
  creating build/temp.mingw_x86_64_clang-cpython-311/src
  creating build/temp.mingw_x86_64_clang-cpython-311/src/pybase64
  clang -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -O3 -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -O3 -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -D__USE_MINGW_ANSI_STDIO=1 -DBASE64_STATIC_DEFINE=1 -Ibase64/include/ -Ibase64/lib/ -I.base64_build -ID:/M/msys64/clang64/include/python3.11 -c src/pybase64/_pybase64.c -o build/temp.mingw_x86_64_clang-cpython-311/src/pybase64/_pybase64.o
  src/pybase64/_pybase64.c:4:10: fatal error: 'config.h' file not found
      4 | #include <config.h>
        |          ^~~~~~~~~~
  1 error generated.
  warning: BuildExt: building extension "pybase64._pybase64" failed: command 'D:\\M\\msys64\\clang64\\bin/clang.exe' failed with exit code 1
```
It expects base64 to be in the directory (`-Ibase64/include/`) but setuptools creates a temporary build directory.

**Comment by mayeut** [comment] 2024-01-06 08:22
The root issue is not related to the temporary build directory at all but to a failure to build the base64 library. The config file will be in `-I.base64_build` in case of success.
Logging is misleading in this case not pointing to the root cause but to a side effect.
If you want a hard failure if the extension is not built, please define `CIBUILDWHEEL=1` environment variable.

I'll add an msys2 workflow to work through the logging issue first, then try to see what's happening in that case.

**Comment by MehdiChinoune** [comment] 2024-01-06 08:28
I see, pybase64 expects "Visual Studio" + "MSVC compiler".

**Closed** 2024-01-06 12:54 UTC
